name: Docker Image CI

on:
  schedule:
  - cron: "30 * * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file  moodle/Dockerfile  --tag cticsjeifsc/moodle:3.9
    
    -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push image
      run: docker push cticsjeifsc/moodle:3.9
